/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Oauth2CallbackRouteImport } from './routes/oauth2.callback'
import { Route as ComplianceTermsRouteImport } from './routes/compliance.terms'
import { Route as CompliancePrivacyRouteImport } from './routes/compliance.privacy'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Oauth2CallbackRoute = Oauth2CallbackRouteImport.update({
  id: '/oauth2/callback',
  path: '/oauth2/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceTermsRoute = ComplianceTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => ComplianceRoute,
} as any)
const CompliancePrivacyRoute = CompliancePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ComplianceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocked': typeof BlockedRoute
  '/compliance': typeof ComplianceRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/compliance/privacy': typeof CompliancePrivacyRoute
  '/compliance/terms': typeof ComplianceTermsRoute
  '/oauth2/callback': typeof Oauth2CallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocked': typeof BlockedRoute
  '/compliance': typeof ComplianceRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/compliance/privacy': typeof CompliancePrivacyRoute
  '/compliance/terms': typeof ComplianceTermsRoute
  '/oauth2/callback': typeof Oauth2CallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocked': typeof BlockedRoute
  '/compliance': typeof ComplianceRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/compliance/privacy': typeof CompliancePrivacyRoute
  '/compliance/terms': typeof ComplianceTermsRoute
  '/oauth2/callback': typeof Oauth2CallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocked'
    | '/compliance'
    | '/privacy'
    | '/terms'
    | '/compliance/privacy'
    | '/compliance/terms'
    | '/oauth2/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocked'
    | '/compliance'
    | '/privacy'
    | '/terms'
    | '/compliance/privacy'
    | '/compliance/terms'
    | '/oauth2/callback'
  id:
    | '__root__'
    | '/'
    | '/blocked'
    | '/compliance'
    | '/privacy'
    | '/terms'
    | '/compliance/privacy'
    | '/compliance/terms'
    | '/oauth2/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlockedRoute: typeof BlockedRoute
  ComplianceRoute: typeof ComplianceRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  Oauth2CallbackRoute: typeof Oauth2CallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth2/callback': {
      id: '/oauth2/callback'
      path: '/oauth2/callback'
      fullPath: '/oauth2/callback'
      preLoaderRoute: typeof Oauth2CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/terms': {
      id: '/compliance/terms'
      path: '/terms'
      fullPath: '/compliance/terms'
      preLoaderRoute: typeof ComplianceTermsRouteImport
      parentRoute: typeof ComplianceRoute
    }
    '/compliance/privacy': {
      id: '/compliance/privacy'
      path: '/privacy'
      fullPath: '/compliance/privacy'
      preLoaderRoute: typeof CompliancePrivacyRouteImport
      parentRoute: typeof ComplianceRoute
    }
  }
}

interface ComplianceRouteChildren {
  CompliancePrivacyRoute: typeof CompliancePrivacyRoute
  ComplianceTermsRoute: typeof ComplianceTermsRoute
}

const ComplianceRouteChildren: ComplianceRouteChildren = {
  CompliancePrivacyRoute: CompliancePrivacyRoute,
  ComplianceTermsRoute: ComplianceTermsRoute,
}

const ComplianceRouteWithChildren = ComplianceRoute._addFileChildren(
  ComplianceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlockedRoute: BlockedRoute,
  ComplianceRoute: ComplianceRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  Oauth2CallbackRoute: Oauth2CallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
