/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileTasksRouteImport } from './routes/profile.tasks'
import { Route as ProfileSessionsHistoryRouteImport } from './routes/profile.sessions-history'
import { Route as ProfileScreenTimeRouteImport } from './routes/profile.screen-time'
import { Route as ProfileConnectedAppsRouteImport } from './routes/profile.connected-apps'
import { Route as LoginWebRouteImport } from './routes/login.web'
import { Route as LoginAppRouteImport } from './routes/login.app'
import { Route as ConnectCallbackRouteImport } from './routes/connect.callback'
import { Route as ComplianceTermsRouteImport } from './routes/compliance.terms'
import { Route as CompliancePrivacyRouteImport } from './routes/compliance.privacy'
import { Route as CallbackSignupWebRouteImport } from './routes/callback.signup.web'
import { Route as CallbackSignupAppRouteImport } from './routes/callback.signup.app'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileTasksRoute = ProfileTasksRouteImport.update({
  id: '/profile/tasks',
  path: '/profile/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSessionsHistoryRoute = ProfileSessionsHistoryRouteImport.update({
  id: '/profile/sessions-history',
  path: '/profile/sessions-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileScreenTimeRoute = ProfileScreenTimeRouteImport.update({
  id: '/profile/screen-time',
  path: '/profile/screen-time',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileConnectedAppsRoute = ProfileConnectedAppsRouteImport.update({
  id: '/profile/connected-apps',
  path: '/profile/connected-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginWebRoute = LoginWebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => LoginRoute,
} as any)
const LoginAppRoute = LoginAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => LoginRoute,
} as any)
const ConnectCallbackRoute = ConnectCallbackRouteImport.update({
  id: '/connect/callback',
  path: '/connect/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceTermsRoute = ComplianceTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => ComplianceRoute,
} as any)
const CompliancePrivacyRoute = CompliancePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ComplianceRoute,
} as any)
const CallbackSignupWebRoute = CallbackSignupWebRouteImport.update({
  id: '/callback/signup/web',
  path: '/callback/signup/web',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackSignupAppRoute = CallbackSignupAppRouteImport.update({
  id: '/callback/signup/app',
  path: '/callback/signup/app',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocked': typeof BlockedRoute
  '/compliance': typeof ComplianceRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/compliance/privacy': typeof CompliancePrivacyRoute
  '/compliance/terms': typeof ComplianceTermsRoute
  '/connect/callback': typeof ConnectCallbackRoute
  '/login/app': typeof LoginAppRoute
  '/login/web': typeof LoginWebRoute
  '/profile/connected-apps': typeof ProfileConnectedAppsRoute
  '/profile/screen-time': typeof ProfileScreenTimeRoute
  '/profile/sessions-history': typeof ProfileSessionsHistoryRoute
  '/profile/tasks': typeof ProfileTasksRoute
  '/profile': typeof ProfileIndexRoute
  '/callback/signup/app': typeof CallbackSignupAppRoute
  '/callback/signup/web': typeof CallbackSignupWebRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocked': typeof BlockedRoute
  '/compliance': typeof ComplianceRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/compliance/privacy': typeof CompliancePrivacyRoute
  '/compliance/terms': typeof ComplianceTermsRoute
  '/connect/callback': typeof ConnectCallbackRoute
  '/login/app': typeof LoginAppRoute
  '/login/web': typeof LoginWebRoute
  '/profile/connected-apps': typeof ProfileConnectedAppsRoute
  '/profile/screen-time': typeof ProfileScreenTimeRoute
  '/profile/sessions-history': typeof ProfileSessionsHistoryRoute
  '/profile/tasks': typeof ProfileTasksRoute
  '/profile': typeof ProfileIndexRoute
  '/callback/signup/app': typeof CallbackSignupAppRoute
  '/callback/signup/web': typeof CallbackSignupWebRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocked': typeof BlockedRoute
  '/compliance': typeof ComplianceRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/compliance/privacy': typeof CompliancePrivacyRoute
  '/compliance/terms': typeof ComplianceTermsRoute
  '/connect/callback': typeof ConnectCallbackRoute
  '/login/app': typeof LoginAppRoute
  '/login/web': typeof LoginWebRoute
  '/profile/connected-apps': typeof ProfileConnectedAppsRoute
  '/profile/screen-time': typeof ProfileScreenTimeRoute
  '/profile/sessions-history': typeof ProfileSessionsHistoryRoute
  '/profile/tasks': typeof ProfileTasksRoute
  '/profile/': typeof ProfileIndexRoute
  '/callback/signup/app': typeof CallbackSignupAppRoute
  '/callback/signup/web': typeof CallbackSignupWebRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocked'
    | '/compliance'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/compliance/privacy'
    | '/compliance/terms'
    | '/connect/callback'
    | '/login/app'
    | '/login/web'
    | '/profile/connected-apps'
    | '/profile/screen-time'
    | '/profile/sessions-history'
    | '/profile/tasks'
    | '/profile'
    | '/callback/signup/app'
    | '/callback/signup/web'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocked'
    | '/compliance'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/compliance/privacy'
    | '/compliance/terms'
    | '/connect/callback'
    | '/login/app'
    | '/login/web'
    | '/profile/connected-apps'
    | '/profile/screen-time'
    | '/profile/sessions-history'
    | '/profile/tasks'
    | '/profile'
    | '/callback/signup/app'
    | '/callback/signup/web'
  id:
    | '__root__'
    | '/'
    | '/blocked'
    | '/compliance'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/compliance/privacy'
    | '/compliance/terms'
    | '/connect/callback'
    | '/login/app'
    | '/login/web'
    | '/profile/connected-apps'
    | '/profile/screen-time'
    | '/profile/sessions-history'
    | '/profile/tasks'
    | '/profile/'
    | '/callback/signup/app'
    | '/callback/signup/web'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlockedRoute: typeof BlockedRoute
  ComplianceRoute: typeof ComplianceRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ConnectCallbackRoute: typeof ConnectCallbackRoute
  ProfileConnectedAppsRoute: typeof ProfileConnectedAppsRoute
  ProfileScreenTimeRoute: typeof ProfileScreenTimeRoute
  ProfileSessionsHistoryRoute: typeof ProfileSessionsHistoryRoute
  ProfileTasksRoute: typeof ProfileTasksRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  CallbackSignupAppRoute: typeof CallbackSignupAppRoute
  CallbackSignupWebRoute: typeof CallbackSignupWebRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/tasks': {
      id: '/profile/tasks'
      path: '/profile/tasks'
      fullPath: '/profile/tasks'
      preLoaderRoute: typeof ProfileTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/sessions-history': {
      id: '/profile/sessions-history'
      path: '/profile/sessions-history'
      fullPath: '/profile/sessions-history'
      preLoaderRoute: typeof ProfileSessionsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/screen-time': {
      id: '/profile/screen-time'
      path: '/profile/screen-time'
      fullPath: '/profile/screen-time'
      preLoaderRoute: typeof ProfileScreenTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/connected-apps': {
      id: '/profile/connected-apps'
      path: '/profile/connected-apps'
      fullPath: '/profile/connected-apps'
      preLoaderRoute: typeof ProfileConnectedAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/web': {
      id: '/login/web'
      path: '/web'
      fullPath: '/login/web'
      preLoaderRoute: typeof LoginWebRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/app': {
      id: '/login/app'
      path: '/app'
      fullPath: '/login/app'
      preLoaderRoute: typeof LoginAppRouteImport
      parentRoute: typeof LoginRoute
    }
    '/connect/callback': {
      id: '/connect/callback'
      path: '/connect/callback'
      fullPath: '/connect/callback'
      preLoaderRoute: typeof ConnectCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/terms': {
      id: '/compliance/terms'
      path: '/terms'
      fullPath: '/compliance/terms'
      preLoaderRoute: typeof ComplianceTermsRouteImport
      parentRoute: typeof ComplianceRoute
    }
    '/compliance/privacy': {
      id: '/compliance/privacy'
      path: '/privacy'
      fullPath: '/compliance/privacy'
      preLoaderRoute: typeof CompliancePrivacyRouteImport
      parentRoute: typeof ComplianceRoute
    }
    '/callback/signup/web': {
      id: '/callback/signup/web'
      path: '/callback/signup/web'
      fullPath: '/callback/signup/web'
      preLoaderRoute: typeof CallbackSignupWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback/signup/app': {
      id: '/callback/signup/app'
      path: '/callback/signup/app'
      fullPath: '/callback/signup/app'
      preLoaderRoute: typeof CallbackSignupAppRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ComplianceRouteChildren {
  CompliancePrivacyRoute: typeof CompliancePrivacyRoute
  ComplianceTermsRoute: typeof ComplianceTermsRoute
}

const ComplianceRouteChildren: ComplianceRouteChildren = {
  CompliancePrivacyRoute: CompliancePrivacyRoute,
  ComplianceTermsRoute: ComplianceTermsRoute,
}

const ComplianceRouteWithChildren = ComplianceRoute._addFileChildren(
  ComplianceRouteChildren,
)

interface LoginRouteChildren {
  LoginAppRoute: typeof LoginAppRoute
  LoginWebRoute: typeof LoginWebRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginAppRoute: LoginAppRoute,
  LoginWebRoute: LoginWebRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlockedRoute: BlockedRoute,
  ComplianceRoute: ComplianceRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ConnectCallbackRoute: ConnectCallbackRoute,
  ProfileConnectedAppsRoute: ProfileConnectedAppsRoute,
  ProfileScreenTimeRoute: ProfileScreenTimeRoute,
  ProfileSessionsHistoryRoute: ProfileSessionsHistoryRoute,
  ProfileTasksRoute: ProfileTasksRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  CallbackSignupAppRoute: CallbackSignupAppRoute,
  CallbackSignupWebRoute: CallbackSignupWebRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
